name: Deploy static site to Azure Web App (Windows)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Zip static site files
        run: |
          zip -r site.zip index.html script.js style.css images web.config

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: drawbridgeaiwindowsuk  # 👈 your new app name
          slot-name: production
          package: site.zip
